export const LOCAL_STATION_DATA = [
  {
    tritonId: "WCRFFM",
    callLetters: "WCRF",
    url: "https://playerservices.streamtheworld.com/api/livestream-redirect/WCRFFM.mp3",
    name: "103.3 FM - Cleveland",
    backgroundColor: "#74a433",
    lat: 41.29679,
    lng: -81.65726,
  },
  {
    tritonId: "KMBIFM",
    callLetters: "KMBI",
    url: "https://playerservices.streamtheworld.com/api/livestream-redirect/KMBIFM.mp3",
    name: "107.9 FM - Spokane",
    backgroundColor: "#74a433",
    lat: 47.57051,
    lng: -117.08334,
  },
  {
    tritonId: "WFCMFM",
    callLetters: "WFCM",
    url: "https://playerservices.streamtheworld.com/api/livestream-redirect/WFCMFM.mp3",
    name: "1200 AM - Nashville",
    backgroundColor: "#74a433",
    lat: 36.208333,
    lng: -86.8725,
  },
  {
    tritonId: "WMBWFM",
    callLetters: "WMBW",
    url: "https://playerservices.streamtheworld.com/api/livestream-redirect/WMBWFM.mp3",
    name: "88.9 FM - Chattanooga",
    backgroundColor: "#74a433",
    lat: 34.96217,
    lng: -85.37786,
  },
  {
    tritonId: "MB2",
    callLetters: "WMFT",
    url: "https://playerservices.streamtheworld.com/api/livestream-redirect/MB2.mp3",
    name: "88.9 FM - Tuscaloosa/Birmingham",
    backgroundColor: "#74a433",
    lat: 33.33871,
    lng: -87.35886,
  },
  {
    tritonId: "WDLMFM",
    callLetters: "WDLM",
    url: "https://playerservices.streamtheworld.com/api/livestream-redirect/WDLMFM.mp3",
    name: "89.3 FM - East Moline",
    backgroundColor: "#74a433",
    lat: 41.54747,
    lng: -90.47485,
  },
  {
    tritonId: "WRMBFM",
    callLetters: "WRMB",
    url: "https://playerservices.streamtheworld.com/api/livestream-redirect/WRMBFM.mp3",
    name: "89.3 FM - South Florida",
    backgroundColor: "#74a433",
    lat: 26.51796,
    lng: -80.17034,
  },
  {
    tritonId: "WGNBFM",
    callLetters: "WGNB",
    url: "https://playerservices.streamtheworld.com/api/livestream-redirect/WGNBFM.mp3",
    name: "89.3 FM - Zeeland",
    backgroundColor: "#74a433",
    lat: 42.83721,
    lng: -85.98831,
  },
  {
    tritonId: "MB2",
    callLetters: "KMBN",
    url: "https://playerservices.streamtheworld.com/api/livestream-redirect/MB2.mp3",
    name: "89.7 FM - Las Cruces",
    backgroundColor: "#74a433",
    lat: 32.2783,
    lng: -106.91191,
  },
  {
    tritonId: "WMBIFM",
    callLetters: "WMBI",
    url: "https://playerservices.streamtheworld.com/api/livestream-redirect/WMBIFM.mp3",
    name: "90.1 FM - Chicago",
    backgroundColor: "#74a433",
    lat: 41.9278,
    lng: -88.00695,
  },
  {
    tritonId: "MB2",
    callLetters: "WJSO",
    url: "https://playerservices.streamtheworld.com/api/livestream-redirect/MB2.mp3",
    name: "90.1 FM - Pikeville",
    backgroundColor: "#74a433",
    lat: 37.46444,
    lng: -82.54528,
  },
  {
    tritonId: "WKESFM",
    callLetters: "WKES",
    url: "https://playerservices.streamtheworld.com/api/livestream-redirect/WKESFM.mp3",
    name: "91.1 FM - St. Petersburg",
    backgroundColor: "#74a433",
    lat: 28.07937,
    lng: -82.04075,
  },
  {
    tritonId: "WFCMFM",
    callLetters: "WFCM",
    url: "https://playerservices.streamtheworld.com/api/livestream-redirect/WFCMFM.mp3",
    name: "91.7 FM - Murfreesboro",
    backgroundColor: "#74a433",
    lat: 35.80019,
    lng: -86.62123,
  },
  {
    tritonId: "MB2",
    callLetters: "WCDC",
    url: "https://playerservices.streamtheworld.com/api/livestream-redirect/MB2.mp3",
    name: "950 AM - Charleston",
    backgroundColor: "#74a433",
    lat: null,
    lng: null,
  },
  {
    tritonId: "WGNRFM",
    callLetters: "WGNR",
    url: "https://playerservices.streamtheworld.com/api/livestream-redirect/WGNRFM.mp3",
    name: "97.9 FM - Indianapolis",
    backgroundColor: "#74a433",
    lat: 40.06235,
    lng: -85.70924,
  },
  {
    tritonId: "WFCMFM",
    callLetters: "WFCM",
    url: "httpss://playerservices.streamtheworld.com/api/livestream-redirect/WFCMFM.mp3",
    name: "98.7 FM - Nashville",
    backgroundColor: "#74a433",
    lat: 35.80019,
    lng: -86.62123,
  },
];
